Вычитка 10 части (ru)
AgentMC/Sao20 pull request #27
Opened 2020-10-04 07:21 UTC by mymedia2

2020-10-04 08:25 UTC, evorios requested changes

2020-10-04 08:25 UTC, evorios commented on Translate/Ru/Part10.md
> +"Так или иначе, а знания Аюхи-самы о компонентах просто необъятные...... В академии мы должны были их изучать весьма серьёзно, но она один за другим называла растения и минералы, о которых мы раньше
`удивилась` -> `удивлялась`
Не думаю, что мы так выражаемся в подобных ситуациях.
Даже если это продолжалось некоторое время, я всё-таки сказал бы об этом как о совершенном действии:
`я очень удивилась`

2020-10-04 08:25 UTC, evorios commented on Translate/Ru/Part10.md
> +Её мысли о Юдзио не давали покоя и затягивали ответ Ренри, так что внезапное повышение могло стать для Тейзы своего рода дедлайном. К тому же Ронье знала, что хоть её подруга и старалась быть весёлой
Лучше заменить слово `дедлайном`

2020-10-04 08:25 UTC, evorios commented on Translate/Ru/Part10.md
> +Однако, печаль Тейзы, видневшаяся в глубине глаз цвета осенних листьев, никуда не девалась, как бы она делала вид, что радостно смеётся.
Предлагаю так:
`Однако, печаль Тейзы, видневшаяся в глубине глаз цвета осенних листьев, никуда не делась, потому как она только делала вид, что радостно смеётся.`

2020-10-04 08:25 UTC, evorios commented on Translate/Ru/Part10.md
> +Тейза, совсем недавно слушавшая разговор с серьёзным выражением лица, сидела, повесив голову и закусив губы, как будто она отчаянно пыталась сдерживать слёзы.
`закусив губы` -> `закусив губу`
Попробуй сам закусить обе губы, либо одну только нижнюю. Очевидно, тут имеется ввиду второй вариант, когда закусываешь одну нижнюю губу.

2020-10-04 08:25 UTC, evorios commented on Translate/Ru/Part10.md
> +Кирито и Асуна не говорили ни слова. Решительность была одной из характерных черт членов Ордена, однако, искренне беспокоясь о чувствах Тейзы, они продолжали молчать.
Мне ближе оригинальный вариант.

2020-10-04 08:25 UTC, evorios commented on Translate/Ru/Part10.md
> +Шимосаки, гонявшийся за Цукигаке и Натсом где-то в центре сада, коротко курлыкнул, подошёл к столу и лизнул пальцы Тейзиной правой руки. Тейза ласково почесала молодого дракона за шею и медленно подн
`почесала... за шею` странно звучит.

2020-10-04 08:25 UTC, evorios commented on Translate/Ru/Part10.md
> +— сразу спросил Кирито, смотря прямо на неё. С тех пор, как они впервые встретились в Академии Искусства Меча, им было знакомо это чувство неизбежности ответа, которое вызывал взгляд его чёрных глаз,
`с трудом выдавила` звучит лучше

2020-10-04 08:25 UTC, evorios commented on Translate/Ru/Part10.md
> +Кирито положил меч в центр стола, он и правда был Мечом Синей Розы — бывшим любимым мечом Юдзио, и это было прекраснейшее Божественное Орудие, которым Кирито продолжал владеть после его смерти.
А если так:
`Кирито положил меч в центр стола, — это и правда был Меч Синей Розы — любимый меч Юдзио`

2020-10-04 08:25 UTC, evorios commented on Translate/Ru/Part10.md
> +Ещё когда Юдзио и Кирито поступали в Академию Искусства Меча, они могли свободно обращаться с этим мечом, Божественным Орудием. А это значит, что их уровень контроля оружия уже тогда достиг 45, уровн
Возможно, так лучше:
`Это значит, что их уровень контроля оружия достиг 45, уровня высших классов. Учитывая это, можно утверждать, что уже тогда они двое вышли на один уровень`

2020-10-04 08:56 UTC, mymedia2 commented on Translate/Ru/Part10.md
> +"Так или иначе, а знания Аюхи-самы о компонентах просто необъятные...... В академии мы должны были их изучать весьма серьёзно, но она один за другим называла растения и минералы, о которых мы раньше
> Результаты поиска "я очень удивлялась" в основном корпусе.
> Найдено 4 документа, 4 вхождения.

https://processing.ruscorpora.ru/search.xml?env=alpha&api=1.0&mycorp=&mysent=&mysize=&mysentsize=&dpp=&spp=&spd=&mydocsize=&mode=main&lang=ru&sort=i_grtagging&nodia=1&text=lexform&req=я+очень+удивлялась

Аюха _называла_, Ронье _удивлялась_.

2020-10-04 08:56 UTC, mymedia2 commented on Translate/Ru/Part10.md
> +Её мысли о Юдзио не давали покоя и затягивали ответ Ренри, так что внезапное повышение могло стать для Тейзы своего рода дедлайном. К тому же Ронье знала, что хоть её подруга и старалась быть весёлой
Почему?

2020-10-04 08:56 UTC, mymedia2 commented on Translate/Ru/Part10.md
> +Однако, печаль Тейзы, видневшаяся в глубине глаз цвета осенних листьев, никуда не девалась, как бы она делала вид, что радостно смеётся.
ok

2020-10-04 08:56 UTC, mymedia2 commented on Translate/Ru/Part10.md
> +Тейза, совсем недавно слушавшая разговор с серьёзным выражением лица, сидела, повесив голову и закусив губы, как будто она отчаянно пыталась сдерживать слёзы.
> Результаты поиска "закусив губы" в основном корпусе.
> Найдено 78 документов, 90 вхождений.

https://processing.ruscorpora.ru/search.xml?env=alpha&api=1.0&mycorp=&mysent=&mysize=&mysentsize=&dpp=&spp=&spd=&mydocsize=&mode=main&lang=ru&sort=i_grtagging&nodia=1&text=lexform&req=закусив+губы

Что не так?

2020-10-04 08:56 UTC, mymedia2 commented on Translate/Ru/Part10.md
> +Шимосаки, гонявшийся за Цукигаке и Натсом где-то в центре сада, коротко курлыкнул, подошёл к столу и лизнул пальцы Тейзиной правой руки. Тейза ласково почесала молодого дракона за шею и медленно подн
Возможно. Как насчёт "почесала ... по шее"?

2020-10-04 08:56 UTC, mymedia2 commented on Translate/Ru/Part10.md
> +— сразу спросил Кирито, смотря прямо на неё. С тех пор, как они впервые встретились в Академии Искусства Меча, им было знакомо это чувство неизбежности ответа, которое вызывал взгляд его чёрных глаз,
Не думаю. Что она из себя _выдавила_?

2020-10-04 08:56 UTC, mymedia2 commented on Translate/Ru/Part10.md
> +Кирито положил меч в центр стола, он и правда был Мечом Синей Розы — бывшим любимым мечом Юдзио, и это было прекраснейшее Божественное Орудие, которым Кирито продолжал владеть после его смерти.
ack

2020-10-04 08:58 UTC, mymedia2 commented
@evorios Спасибо за комментарии! Немного проправил текст.

2020-10-04 11:33 UTC, AgentMC requested changes
Воу-воу-воу, ребят. Не так быстро :)  Признателен за прочитку и за желание сделать всё лучше, но давайте добавим немного конструктива.

Тут смесь трёх вещей: опечатки, пунктуация и полная переработка некоторых фраз (стилистическая редактура). 

Так вот, сразу говорю, последнее вообще не принимается. По двум причинам.
1) это всё-таки моя автораская работа, и стиль изложения здесь не "неправильный" или "нелитературный", а "мой". Это перевод японской книги на русский, а не русская книга по японскому оригиналу, поэтому ей не следует менять оригинал столь сильно в угоду благозвучности.
2) многие изменения, что я вижу, существенно меняют/искажают смысл текста, а то и вовсе содержат опечатки.

Но я готов принять исправления опечаток и пунктуации отдельно. Если вы можете переработать PR так, чтобы осталось только это, без стилистических изменений, то я его рассмотрю. Если же нет, то я выборочно пройдусь по этому PR и выборочно замёржу изменения.

2020-10-05 05:42 UTC, mymedia2 commented
@AgentMC Прежде всего выражаю огромную благодарность за ваш труд и перевод арки "Колыбель луны". Видно, что под конец вам хотелось побыстрее закончить проект, и огрехи стали проявляться в тексте чаще. Конечно, хотелось бы довести дело до конца и исправить некоторые языковые новшества, для которых, на мой взгляд, место в переводной книге на русском не совсем подходящее.

Увы, как-то разделять этот pull request затруднительно. Поэтому я не будут этим заниматься. Тем более, что это создаст сложности при обратном объединении правок. Хозяин — барин, но я буду рад, если вы воспользуетесь хоть какими-нибудь моими наработками отсюда.

> 2. многие изменения, что я вижу, существенно меняют/искажают смысл текста, а то и вовсе содержат опечатки.

К сожалению, конрентная суть претензий не ясна :neutral_face:

2020-10-24 20:38 UTC, merged

2020-10-24 20:54 UTC, AgentMC commented
Просмотрел детально и смерджил то, что получилось. Поскольку я оставил оригинальный коммит как есть, а поверх навертел роллбеков, Гитхаб считает что ПР смерджен целоком, но это не совсем так.

* Что принято: https://github.com/AgentMC/Sao20/commit/7bb30c51d2d1266ad015ae576adc4c6a05fbd13d
* Что не принято: https://github.com/AgentMC/Sao20/commit/3ead79f4343f0a8a2fc76933f894e7edf6454a52

(Нажмите Load Diff в обоих случаях)

Принял в итоге намного больше, чем изначально думал, в основном потому что при первом просмотре мне почему-то в основном попались вещи, которые я в итоге не принял %-)

Не принято:

* необоснованные замены синонимов и синонимичных выражений, не несущие полезной нагрузки  
* изменения в оценке и речи персонажей, нарушающие их модель поведения
* изменения, не согласующиеся с повествованием и неоправданно переставляющие акценты
* не надо пытаться, пожалуйста, "сделать лучше" там, где это совсем не требуется :)
* много в конце - видимо вы тоже устали ;) Там неизвестно зачем вообще были заменены действия персонажей...(???)

Спасибо за вашу работу. Добавляю на 1 страницу.